name: EasyBarrier
description: EasyBarrier
main: com.connorlinfoot.easybarrier.EasyBarrier
version: 1.1-SNAPSHOT
authors: [Connor Linfoot]
commands:
  eb:
    description: EasyBarrier command
permissions:
  easybarrier.bypass:
    default: op
  easybarrier.block:
    default: op